spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ajmalch/config-repo.git
          search-paths: MASTER
server:
  port: 8888
management:
  security:
    enabled: false